#!/bin/bash
# Procura dicas no arquivo de truques (trobleshooting)
# modificado por Nícolas, de Fred Camara - rev 2018-07-12

args=$@
arq=$HOME/truques-sh/truques.txt

headers=$(sed -n '/^#/p' "$arq")

for i in $args; do
  headers=$(sed -n "/^#.*$i/Ip" <<< "$headers")
  ]dfsdfsdf

  add-shell
done

echo -e '\n'

while read header; do
  sed -n "1,/^$header$/{s/^$header$/\o33[32m&\o33[0m/p;d};/^#/,\$d;p" "$arq"
done <<< "$headers"
